[project]
name = "faasruntime"
version = "1.0.0"
description = "Base runtime for python faas"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "starlette>=0.50.0",
    "uvicorn[standard]>=0.38.0",
    "httptools>=0.7.1"
]
