services:
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686" # The UI
#      - "9411:9411"   # Zipkin Protocol Port (Envoy uses this)
  xds_connector:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GRPC_PORT=0.0.0.0:50051
      - NODE_ID=local_node
      - REST_PORT=8081
    networks:
      - proxy-net
    depends_on:
      - gate
      - envoy

  gate:
    image: openresty/openresty:alpine
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    ports:
      - "8080:80" # Der Gate-Port f√ºr deinen Traffic
    networks:
      - proxy-net
      - layers-messaging-net

  # Prometheus Server
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.ym
    depends_on:
      - envoy
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "7080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - envoy

  envoy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9901:9901"   # Admin API
      #- "10000:10000" # Listener
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "control-plane:host-gateway"
    restart: unless-stopped
    networks:
      - proxy-net
      - faas-net

  backend:
    image: python:3
    ports:
      - "8000:8000"
    command: python -m http.server 8000
    networks:
      - faas-net

  mosquitto:
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT
      - "8883:8883"    # MQTTS (secure)
      - "9001:9001"    # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - layers-messaging-net

networks:
  monitor-net:
  proxy-net:
  faas-net:
  layers-messaging-net: