services:
  #jaeger:
  #  image: jaegertracing/all-in-one:latest
  #  environment:
  #    # 1. ADD THIS to enable Port 9411
  #    - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  #  ports:
  #    - "16686:16686" # The UI
  #    - "9411:9411"   # Zipkin Protocol Port (Envoy uses this)
  #  networks:
  #    - monitor-net
  xds_connector:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GRPC_PORT=0.0.0.0:50051
      - NODE_ID=local_node
      - REST_PORT=8081
    networks:
      - proxy-net
      - layers-messaging-net
      - managing-net
    depends_on:
      - gate
      - envoy

  gate:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    environment:
      - REST_PORT=7071
    networks:
      - proxy-net
      - layers-messaging-net
      - managing-net
    depends_on:
      - envoy

  envoy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9901:9901"   # Admin API
      #- "10000:10000" # Listener
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - shared-logs:/shared/logs
    extra_hosts:
      - "control-plane:host-gateway"
    restart: unless-stopped
    networks:
      - proxy-net
      - faas-net
      - monitor-net
      - layers-messaging-net
    environment:
      - REDIS_ADDR=redis-messanger:6379
      - TRACKER_FAAS_REDIS_TOPIC=FAASTracker
    depends_on:
      - redis

  statsd-listener:
    build:
      context: ./statsdListener/
      dockerfile: Dockerfile
    environment:
      - REDIS_MESSANGER_URL=http://redis-rest-pusher:7071
    network_mode: service:envoy

  redis:
    image: redis:alpine
    container_name: redis-messanger
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    networks:
      - layers-messaging-net
      - managing-net
      - faas-net

  redis-rest-pusher:
    build:
      context: .
      dockerfile: redis-rest-pusher/Dockerfile
    ports:
      - "7071:7071"
    environment:
      - REDIS_ADDR=redis-messanger:6379
      - REST_PORT=7071
      - ADD_FAAS_REDIS_TOPIC=newFAASCounter
      - REMOVE_FAAS_REDIS_TOPIC=removingFAASCounter
    networks:
      - layers-messaging-net

  orchestrator:
    build:
      context: .
      dockerfile: ./orchestration/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./faasRuntime:/app/faasRuntime
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - REDIS_URL=redis-messanger
      - FAAS_CONFIG_YAML_PATH=./faasRuntime/global-function-definition.yml
      - FAAS_ROOT_FOLDER_PATH=./faasRuntime
    networks:
      - managing-net
    depends_on:
      - envoy
      - xds_connector
      - redis
      - redis-rest-pusher
      - gate


volumes:
  shared-logs:

networks:
  monitor-net:
  proxy-net:
  faas-net:
  layers-messaging-net:
  managing-net: