global:
  scrape_interval: 10ms  # Scrape often for your scaling logic

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'


rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: 'envoy_stats'
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['envoy:9901'] # 'envoy' matches the service name in Docker Compose